src/java/proy/jpa/entity/Profesor.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proy.jpa.entity;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author NOELIA
 */
@Entity
@Table(name = "profesor")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Profesor.findAll", query = "SELECT p FROM Profesor p")
    , @NamedQuery(name = "Profesor.findByIdProfesor", query = "SELECT p FROM Profesor p WHERE p.idProfesor = :idProfesor")
    , @NamedQuery(name = "Profesor.findByNombres", query = "SELECT p FROM Profesor p WHERE p.nombres = :nombres")
    , @NamedQuery(name = "Profesor.findByApellidos", query = "SELECT p FROM Profesor p WHERE p.apellidos = :apellidos")
    , @NamedQuery(name = "Profesor.findByI", query = "SELECT p FROM Profesor p WHERE p.i = :i")
    , @NamedQuery(name = "Profesor.findByDireccion", query = "SELECT p FROM Profesor p WHERE p.direccion = :direccion")
    , @NamedQuery(name = "Profesor.findByEmail", query = "SELECT p FROM Profesor p WHERE p.email = :email")})
public class Profesor implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "idProfesor")
    private Integer idProfesor;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "Nombres")
    private String nombres;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "Apellidos")
    private String apellidos;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "I")
    private String i;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "Direccion")
    private String direccion;
    // @Pattern(regexp="[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", message="Correo electrónico no válido")//if the field contains email address consider using this annotation to enforce field validation
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "Email")
    private String email;

    public Profesor() {
    }

    public Profesor(Integer idProfesor) {
        this.idProfesor = idProfesor;
    }

    public Profesor(Integer idProfesor, String nombres, String apellidos, String i, String direccion, String email) {
        this.idProfesor = idProfesor;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.i = i;
        this.direccion = direccion;
        this.email = email;
    }

    public Integer getIdProfesor() {
        return idProfesor;
    }

    public void setIdProfesor(Integer idProfesor) {
        this.idProfesor = idProfesor;
    }

    public String getNombres() {
        return nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public String getApellidos() {
        return apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public String getI() {
        return i;
    }

    public void setI(String i) {
        this.i = i;
    }

    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idProfesor != null ? idProfesor.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Profesor)) {
            return false;
        }
        Profesor other = (Profesor) object;
        if ((this.idProfesor == null && other.idProfesor != null) || (this.idProfesor != null && !this.idProfesor.equals(other.idProfesor))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "proy.jpa.entity.Profesor[ idProfesor=" + idProfesor + " ]";
    }
    
}

src/java/Login/ProfesorController.java
package Login;

import proy.jpa.entity.Profesor;
import Login.util.JsfUtil;
import Login.util.PaginationHelper;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("profesorController")
@SessionScoped
public class ProfesorController implements Serializable {

    private Profesor current;
    private DataModel items = null;
    @EJB
    private Login.ProfesorFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public ProfesorController() {
    }

    public Profesor getSelected() {
        if (current == null) {
            current = new Profesor();
            selectedItemIndex = -1;
        }
        return current;
    }

    private ProfesorFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Profesor) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Profesor();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("ProfesorCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Profesor) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("ProfesorUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Profesor) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("ProfesorDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Profesor getProfesor(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Profesor.class)
    public static class ProfesorControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ProfesorController controller = (ProfesorController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "profesorController");
            return controller.getProfesor(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Profesor) {
                Profesor o = (Profesor) object;
                return getStringKey(o.getIdProfesor());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Profesor.class.getName());
            }
        }

    }

}

web/profesor/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateProfesorTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateProfesorLabel_idProfesor}" for="idProfesor" />
                    <h:inputText id="idProfesor" value="#{profesorController.selected.idProfesor}" title="#{bundle.CreateProfesorTitle_idProfesor}" required="true" requiredMessage="#{bundle.CreateProfesorRequiredMessage_idProfesor}"/>
                    <h:outputLabel value="#{bundle.CreateProfesorLabel_nombres}" for="nombres" />
                    <h:inputText id="nombres" value="#{profesorController.selected.nombres}" title="#{bundle.CreateProfesorTitle_nombres}" required="true" requiredMessage="#{bundle.CreateProfesorRequiredMessage_nombres}"/>
                    <h:outputLabel value="#{bundle.CreateProfesorLabel_apellidos}" for="apellidos" />
                    <h:inputText id="apellidos" value="#{profesorController.selected.apellidos}" title="#{bundle.CreateProfesorTitle_apellidos}" required="true" requiredMessage="#{bundle.CreateProfesorRequiredMessage_apellidos}"/>
                    <h:outputLabel value="#{bundle.CreateProfesorLabel_i}" for="i" />
                    <h:inputText id="i" value="#{profesorController.selected.i}" title="#{bundle.CreateProfesorTitle_i}" required="true" requiredMessage="#{bundle.CreateProfesorRequiredMessage_i}"/>
                    <h:outputLabel value="#{bundle.CreateProfesorLabel_direccion}" for="direccion" />
                    <h:inputText id="direccion" value="#{profesorController.selected.direccion}" title="#{bundle.CreateProfesorTitle_direccion}" required="true" requiredMessage="#{bundle.CreateProfesorRequiredMessage_direccion}"/>
                    <h:outputLabel value="#{bundle.CreateProfesorLabel_email}" for="email" />
                    <h:inputText id="email" value="#{profesorController.selected.email}" title="#{bundle.CreateProfesorTitle_email}" required="true" requiredMessage="#{bundle.CreateProfesorRequiredMessage_email}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{profesorController.create}" value="#{bundle.CreateProfesorSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{profesorController.prepareList}" value="#{bundle.CreateProfesorShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateProfesorIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/profesor/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditProfesorTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditProfesorLabel_idProfesor}" for="idProfesor" />
                    <h:inputText id="idProfesor" value="#{profesorController.selected.idProfesor}" title="#{bundle.EditProfesorTitle_idProfesor}" required="true" requiredMessage="#{bundle.EditProfesorRequiredMessage_idProfesor}"/>
                    <h:outputLabel value="#{bundle.EditProfesorLabel_nombres}" for="nombres" />
                    <h:inputText id="nombres" value="#{profesorController.selected.nombres}" title="#{bundle.EditProfesorTitle_nombres}" required="true" requiredMessage="#{bundle.EditProfesorRequiredMessage_nombres}"/>
                    <h:outputLabel value="#{bundle.EditProfesorLabel_apellidos}" for="apellidos" />
                    <h:inputText id="apellidos" value="#{profesorController.selected.apellidos}" title="#{bundle.EditProfesorTitle_apellidos}" required="true" requiredMessage="#{bundle.EditProfesorRequiredMessage_apellidos}"/>
                    <h:outputLabel value="#{bundle.EditProfesorLabel_i}" for="i" />
                    <h:inputText id="i" value="#{profesorController.selected.i}" title="#{bundle.EditProfesorTitle_i}" required="true" requiredMessage="#{bundle.EditProfesorRequiredMessage_i}"/>
                    <h:outputLabel value="#{bundle.EditProfesorLabel_direccion}" for="direccion" />
                    <h:inputText id="direccion" value="#{profesorController.selected.direccion}" title="#{bundle.EditProfesorTitle_direccion}" required="true" requiredMessage="#{bundle.EditProfesorRequiredMessage_direccion}"/>
                    <h:outputLabel value="#{bundle.EditProfesorLabel_email}" for="email" />
                    <h:inputText id="email" value="#{profesorController.selected.email}" title="#{bundle.EditProfesorTitle_email}" required="true" requiredMessage="#{bundle.EditProfesorRequiredMessage_email}"/>
                </h:panelGrid>
                <h:commandLink action="#{profesorController.update}" value="#{bundle.EditProfesorSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditProfesorViewLink}"/>
                <br />
                <h:commandLink action="#{profesorController.prepareList}" value="#{bundle.EditProfesorShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditProfesorIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/profesor/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListProfesorTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListProfesorEmpty}" rendered="#{profesorController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{profesorController.items.rowCount > 0}">
                    <h:outputText value="#{profesorController.pagination.pageFirstItem + 1}..#{profesorController.pagination.pageLastItem + 1}/#{profesorController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{profesorController.previous}" value="#{bundle.Previous} #{profesorController.pagination.pageSize}" rendered="#{profesorController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{profesorController.next}" value="#{bundle.Next} #{profesorController.pagination.pageSize}" rendered="#{profesorController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{profesorController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListProfesorTitle_idProfesor}"/>
                            </f:facet>
                            <h:outputText value="#{item.idProfesor}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListProfesorTitle_nombres}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombres}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListProfesorTitle_apellidos}"/>
                            </f:facet>
                            <h:outputText value="#{item.apellidos}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListProfesorTitle_i}"/>
                            </f:facet>
                            <h:outputText value="#{item.i}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListProfesorTitle_direccion}"/>
                            </f:facet>
                            <h:outputText value="#{item.direccion}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListProfesorTitle_email}"/>
                            </f:facet>
                            <h:outputText value="#{item.email}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{profesorController.prepareView}" value="#{bundle.ListProfesorViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{profesorController.prepareEdit}" value="#{bundle.ListProfesorEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{profesorController.destroy}" value="#{bundle.ListProfesorDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{profesorController.prepareCreate}" value="#{bundle.ListProfesorCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListProfesorIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/profesor/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewProfesorTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewProfesorLabel_idProfesor}"/>
                    <h:outputText value="#{profesorController.selected.idProfesor}" title="#{bundle.ViewProfesorTitle_idProfesor}"/>
                    <h:outputText value="#{bundle.ViewProfesorLabel_nombres}"/>
                    <h:outputText value="#{profesorController.selected.nombres}" title="#{bundle.ViewProfesorTitle_nombres}"/>
                    <h:outputText value="#{bundle.ViewProfesorLabel_apellidos}"/>
                    <h:outputText value="#{profesorController.selected.apellidos}" title="#{bundle.ViewProfesorTitle_apellidos}"/>
                    <h:outputText value="#{bundle.ViewProfesorLabel_i}"/>
                    <h:outputText value="#{profesorController.selected.i}" title="#{bundle.ViewProfesorTitle_i}"/>
                    <h:outputText value="#{bundle.ViewProfesorLabel_direccion}"/>
                    <h:outputText value="#{profesorController.selected.direccion}" title="#{bundle.ViewProfesorTitle_direccion}"/>
                    <h:outputText value="#{bundle.ViewProfesorLabel_email}"/>
                    <h:outputText value="#{profesorController.selected.email}" title="#{bundle.ViewProfesorTitle_email}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{profesorController.destroyAndView}" value="#{bundle.ViewProfesorDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewProfesorEditLink}"/>
                <br />
                <h:commandLink action="#{profesorController.prepareCreate}" value="#{bundle.ViewProfesorCreateLink}" />
                <br />
                <h:commandLink action="#{profesorController.prepareList}" value="#{bundle.ViewProfesorShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewProfesorIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>